version: '3'

services:

  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: hsdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
    ports:
      - "5435:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data

  django:
    image: python:3.11
    volumes:
      - {hydroserver-api-services}:/app
      - staticfiles:/app/staticfiles
    working_dir: /app
    command:
      - sh
      - -c
      - |
        pip install -r requirements.txt
        python manage.py migrate
        python manage.py collectstatic --noinput
        python manage.py runserver 0.0.0.0:8000
    depends_on:
      - timescaledb

  nodejs:
    image: node:latest
    working_dir: /app
    volumes:
      - {hydroserver-data-management-app}:/app
    command:
      - /bin/sh
      - -c
      - |
        npm install
        npm run docker-dev

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - staticfiles:/staticfiles
    ports:
      - "3030:80"
    depends_on:
      - django
      - nodejs

volumes:
  postgresql_data:
  staticfiles:
